# Generated by Django 4.2.7 on 2023-11-09 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaCine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo_de_entrada', models.CharField(max_length=255)),
                ('Hora', models.DateTimeField()),
                ('Fecha', models.DateField()),
                ('butaca', models.CharField(max_length=255)),
                ('sala', models.CharField(max_length=255)),
                ('nombre_cine', models.CharField(max_length=255)),
            ],
        ),
    ]
