# Generated by Django 4.2.7 on 2023-11-20 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('peliculas', '0001_initial'),
        ('entrada', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_entrada', models.CharField(max_length=50, unique=True)),
                ('hora', models.TimeField()),
                ('fecha', models.DateField()),
                ('butaca', models.CharField(max_length=10)),
                ('sala', models.CharField(max_length=50)),
                ('nombre_cine', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='clientes.cliente')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='peliculas.pelicula')),
            ],
        ),
        migrations.DeleteModel(
            name='EntradaCine',
        ),
    ]
